apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxes.mycompany.com
spec:
  group: mycompany.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: nginxes
    singular: nginx
    kind: Nginx
    shortNames:
      - ngx
