apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: default
data:
  log_level: INFO
  game.properties: |
    a=1
    b=2
    c=dd

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: myapplb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8787

---
apiVersion: extensions/v1beta1
kind:  Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapplb
    spec:
      containers:
      - name: myapp
        image: registry.self/jw/myapp:v5
        ports:
        - containerPort: 8787
        env:
        - name: TEST_ENV
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: game.properties
        volumeMounts:
        - name: mysecret
          mountPath: /etc/secret
          readOnly: true
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
      volumes:
      - name: mysecret
        secret:
          secretName: mysecret
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels