/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	mycodev1alpha1 "k8s-learn/apiserver/pkg/apis/mycode/v1alpha1"
	clientset "k8s-learn/apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "k8s-learn/apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "k8s-learn/apiserver/pkg/client/listers_generated/mycode/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyControllerInformer provides access to a shared informer and lister for
// MyControllers.
type MyControllerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MyControllerLister
}

type myControllerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyControllerInformer constructs a new informer for MyController type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyControllerInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyControllerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyControllerInformer constructs a new informer for MyController type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyControllerInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycodeV1alpha1().MyControllers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycodeV1alpha1().MyControllers(namespace).Watch(options)
			},
		},
		&mycodev1alpha1.MyController{},
		resyncPeriod,
		indexers,
	)
}

func (f *myControllerInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyControllerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myControllerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mycodev1alpha1.MyController{}, f.defaultInformer)
}

func (f *myControllerInformer) Lister() v1alpha1.MyControllerLister {
	return v1alpha1.NewMyControllerLister(f.Informer().GetIndexer())
}
