apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-user
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: app-user-bind
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-role
subjects:
- kind: ServiceAccount
  name: app-user
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-role
  namespace: default
  labels:
    app: myapp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "list", "watch"]

---
kind: Pod
apiVersion: v1
metadata:
  name: testsa
spec:
  serviceAccountName: app-user
  containers:
  - name: satest
    image:  registry.self/jw/api:v1
    ports:
    - containerPort: 80
